.TH clreol 3 "Julio de 2004" "libconio 1.0.0" \

.SH NOMBRE
clreol \- borrar caracteres de una linea

.SH SINOPSIS
.B
#include <stdio.h>
.PP
.BI "void clreol(void);"

.SH DESCRIPCIÓN
Borra los caracteres de un renglón desde donde se encuentra 
el cursor hasta el final de la línea

.SH VEA TAMBIÉN 
.BR "clrscr "(3), "wherex "(3), "
.BR wherey "(3), "textcolor "(3), "textbackground "(3), " 
.BR cgetch "(3), "cgetche "(3) "
.BR gotoxy (3)



