.TH clrscr 3 "Julio de 2004" "libconio 1.0.0" \


.SH NOMBRE
clrscr \- limpiar pantalla

.SH SINOPSIS
.B
#include <conio.h>
.PP
.BI "void clrscr(void);"

.SH DESCRIPCION
clrscr limpia la pantalla y coloca el cursor en la posicion 0,0

.SH VEA TAMBIÉN 
.BR clreol "(3), "wherex "(3), "
.BR wherey "(3), "textcolor "(3), "textbackground "(3), " 
.BR cgetch "(3), "cgetche "(3) "
.BR gotoxy (3)
