.TH gotoxy 3 "Julio de 2004" "libconio 1.0.0" 

.SH NOMBRE
gotoxy \- posiciona el cursor en la pantalla

.SH SINOPSIS
.B
#include <stdio.h>
.PP
.BI "void gotoxy(int" " x" ", int " y );

.SH DESCRIPCIÓN
gotoxy coloca el cursor en el renglon y columna especificados, siendo
.I x 
la columna y 
.I y 
el renglon.

.SH VEA TAMBIÉN 
.BR clreol "(3), "clrscr "(3), "wherex "(3), "
.BR wherey "(3), "textcolor "(3), "textbackground "(3), " 
.BR getch "(3), "getche "(3) "

